# Generated by Django 3.2.13 on 2022-05-02 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('current', models.BooleanField(default=True)),
                ('end', models.DateField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subduty', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.duty')),
            ],
        ),
        migrations.AddField(
            model_name='duty',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.job'),
        ),
    ]
