# Generated by Django 3.2.13 on 2022-05-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20220505_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subduty',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='techbullet',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technology',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
