version: '3.8'

services:
  web:
    build: 
      context: ./app
      dockerfile: ./Dockerfile
    command: gunicorn resumebuilder.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - /tmp/docker-files:/tmp/docker-files
    expose:
      - 8000
    env_file:
      - env/.env.app
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - web
    env_file:
      - env/.env.nginx



volumes:
  static_volume:
