version: '3.8'

services:
  web:
    build: 
      context: ./app
      dockerfile: ./Dockerfile
    command: gunicorn resumebuilder.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - env/.env.app
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env/.env.db
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - certbot:/var/www/certbot/www:/var/www/certbot
      - certificates:./certbot/conf:/etc/nginx/ssl/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot:/var/www/certbot/www:/var/www/certbot
      - certificates:/var/www/certbot/conf/:/etc/letsencrypt/

volumes:
  postgres_data:
  static_volume:
  certbot:
  certificates: