# Generated by Django 3.2.13 on 2022-05-05 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifications',
            name='badge',
            field=models.ImageField(default='images/480px-No_image_available.svg.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='certifications',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
